title: Leo Jacoby # your name (or website title) here
#logo: "/images/vlade.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h3>About me</h3>
  <p>I'm on a gap year and will head to Stanford in the Fall of 2021. I graduated high school from the Branson School in Marin County, CA.  I love coding and statistics. I do
    my web and mobile devlopment with Node.js and React and my statistical analysis with R. I post my
    projects on this site, so please check them out and reach out to me with questions, feedback, or to share
    something related that you've done.  I'm always looking for cool people, projects, and opportunities! </p>
  <br>
  <br>
   <p>Email: <a href="mailto:leojacoby@gmail.com">leojacoby@gmail.com</a>
   <p>Twitter: <a href="https://twitter.com/LeoTheprocess21">@leotheprocess21</a></p>
   <p><a href="https://www.linkedin.com/in/leo-jacoby-080898142/">View My LinkedIn Profile</a></p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID her
